/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package microft.software.pcbuildaid.UI;

import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import microft.software.pcbuildaid.PCBuildData.GameData;
import microft.software.pcbuildaid.PCBuildData.Hardware.Base.EnumKeyStrings;
import microft.software.pcbuildaid.PCBuildData.Hardware.Base.Hardware;
import microft.software.pcbuildaid.PCBuildData.Hardware.*;
import microft.software.pcvuildaid.calculators.PCBuild;

/**
 *
 * @author marcc
 */
public class HardwarePicker extends javax.swing.JFrame {
    private PCBuild pc;
    private EnumHardwareType hwType;
    
    /**
     * Creates new form CPUPicker
     * @param pc
     * @param hwType
     */
    public HardwarePicker(PCBuild pc, EnumHardwareType hwType) {
        initComponents();
        this.pc = pc;
        this.hwType = hwType;
        
        populateTable();
    }
    
    public void populateTable(){
        final Class[] columnClasses;
        final String[] headers;
        final Object[][] data; // [row][col]
        
        ArrayList<Hardware> hw = new ArrayList<>();
                
        switch(hwType){
            case CPU:
                // Set the headers (First four columns are standard and set later)
                headers = new String[]{"","","","",
                    EnumKeyStrings.CORES.getKeyText(),
                    EnumKeyStrings.CAN_OVERCLOCK.getKeyText(),
                    EnumKeyStrings.WATTAGE.getKeyText(),
                    EnumKeyStrings.MAX_MEM_CHAN.getKeyText(),
                    EnumKeyStrings.CPU_SOCKET.getKeyText()
                };                
                // Set the column classes
                columnClasses = new Class[]{String.class, String.class, Integer.class, Integer.class,
                    Integer.class, Boolean.class, Integer.class, Integer.class, String.class
                };
                
                // Populate the data.
                data = new Object[GameData.cpus.size()][columnClasses.length];
                int count = 0;
                for(CPU x:GameData.cpus){
                    hw.add(x);
                    data[count][4] = x.getNumberOfCores();
                    data[count][5] = x.isOverclockable();
                    data[count][6] = x.getWattage();
                    data[count][7] = x.getMaxMemChannels();
                    data[count++][8] = x.getSocketType();
                }
                
                this.tblMain.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                break;
            default:
                columnClasses = new Class[]{String.class, String.class, Integer.class, Integer.class};
                data = new Object[][]{};
                headers = new String[4];
        }
        headers[0] = EnumKeyStrings.MANUFACTURER.getKeyText();
        headers[1] = EnumKeyStrings.PART_NAME.getKeyText();
        headers[2] = EnumKeyStrings.LEVEL.getKeyText();
        headers[3] = EnumKeyStrings.PRICE.getKeyText();
        for(int i=0; i<GameData.cpus.size(); ++i){
            data[i][0]=hw.get(i).getManufacturer();
            data[i][1]=hw.get(i).getPartName();
            data[i][2]=hw.get(i).getLevel();
            data[i][3]=hw.get(i).getPrice();
        }
        
        DefaultTableModel dtm = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return columnClasses[columnIndex];
            }

            @Override
            public Object getValueAt(int row, int column) {
                return data[row][column];
            }

            @Override
            public int getColumnCount() {
                return data[0].length;
            }

            @Override
            public int getRowCount() {
                return data.length;
            }

            @Override
            public String getColumnName(int column) {
                //return super.getColumnName(column); //To change body of generated methods, choose Tools | Templates.
                return headers[column];
            }
            
            
        };
        
        tblMain.setModel(dtm);
        tblMain.setAutoCreateRowSorter(true);      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMain = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnOK.setText("OK");
        btnOK.setEnabled(false);
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        tblMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMainMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOK)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        int selRow = this.tblMain.getSelectedRow();
        if(selRow < 0) return;
        this.pc.setCpu(GameData.cpus.get(selRow));
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_btnOKActionPerformed

    private void tblMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMainMouseClicked
        this.btnOK.setEnabled(this.tblMain.getSelectedRowCount() > 0);
    }//GEN-LAST:event_tblMainMouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblMain;
    // End of variables declaration//GEN-END:variables
}
