/*
 * The MIT License
 *
 * Copyright 2020 Marc Cabot.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package microft.software.pcbuildaid.ui;

import java.awt.Color;
import java.awt.GraphicsConfiguration;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import static java.util.Objects.isNull;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import microft.software.pcbuildaid.PCBuildData.PCBuildData;
import microft.software.pcbuildaid.PCBuildData.PCBuildSourceData;


/**
 *
 * @author Marc Cabot
 */
public final class MainUI extends javax.swing.JFrame {

    private PCBuildSourceData sourceData;
    private final PCBuilder[] pcBuilders = new PCBuilder[3];
    private MonitorDisplay monitorDisplays[];
    private final ArrayList<PCBuilder> benches = new ArrayList<>();
    
    /**
     * Creates new form Main
     */
    
    public MainUI(GraphicsConfiguration gc){
        super(gc);
        initComponents();
        this.getContentPane().setBackground(Color.LIGHT_GRAY);
        monitorDisplays = new MonitorDisplay[PCBuildData.getNumberOfMonitors()];
        for(int i=0; i<PCBuildData.getNumberOfMonitors(); i++)
            monitorDisplays[i] = new MonitorDisplay(PCBuildData.getGraphicsConfiguration(i), i);
        this.updateCurrentMonitor();
        loadGameData();
        
        PCBuildData.setLevel(Integer.parseInt(PCBuildData.getSetting("gameLevel", "1")));
        
        moveLevel(0);
    }
    
    public void moveLevel(int inc){
        int newLevel = PCBuildData.getLevel() + inc;
        if(newLevel<1)newLevel = 1; if(newLevel > 100) newLevel = 100;
        this.txtLevel.setText(Integer.toString(newLevel));
        PCBuildData.setLevel(newLevel);
        PCBuildData.setSetting("gameLevel", Integer.toString(newLevel));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dirChooser = new javax.swing.JFileChooser();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtGameFile = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnLevelDown = new javax.swing.JButton();
        txtLevel = new javax.swing.JTextField();
        btnLevelUp = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        tbMonitor = new javax.swing.JToggleButton();
        btnMonitorDwn = new javax.swing.JButton();
        btnMonitorUp = new javax.swing.JButton();
        txtMonitor = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnQuickBench = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnShowBench = new javax.swing.JButton();
        btnDeleteBench = new javax.swing.JButton();
        txtNewBenchName = new javax.swing.JTextField();
        lstBenches = new javax.swing.JComboBox<>();

        dirChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 240, 240));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setText("PC Builder Game Directory:");

        txtGameFile.setEditable(false);
        txtGameFile.setText("jTextField1");

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGameFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtGameFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_med.png"))); // NOI18N

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("My Level");

        btnLevelDown.setText("-");
        btnLevelDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLevelDownActionPerformed(evt);
            }
        });

        txtLevel.setEditable(false);
        txtLevel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtLevel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLevel.setText("0");

        btnLevelUp.setText("+");
        btnLevelUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLevelUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnLevelDown)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLevel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLevelUp)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLevelDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLevel)
                    .addComponent(btnLevelUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        tbMonitor.setText("Monitor");
        tbMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbMonitorActionPerformed(evt);
            }
        });

        btnMonitorDwn.setText("-");
        btnMonitorDwn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonitorDwnActionPerformed(evt);
            }
        });

        btnMonitorUp.setText("+");
        btnMonitorUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonitorUpActionPerformed(evt);
            }
        });

        txtMonitor.setEditable(false);
        txtMonitor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtMonitor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMonitor.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbMonitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnMonitorDwn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMonitor, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMonitorUp)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbMonitor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMonitorDwn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMonitorUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMonitor))
                .addContainerGap())
        );

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnQuickBench.setText("Quick Bench");
        btnQuickBench.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickBenchActionPerformed(evt);
            }
        });

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnShowBench.setText("Show");
        btnShowBench.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowBenchActionPerformed(evt);
            }
        });

        btnDeleteBench.setText("Delete");
        btnDeleteBench.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBenchActionPerformed(evt);
            }
        });

        txtNewBenchName.setText("New Bench Name");

        lstBenches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstBenchesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnQuickBench)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnShowBench, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteBench, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtNewBenchName)
                    .addComponent(lstBenches, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuickBench)
                    .addComponent(btnCreate)
                    .addComponent(btnShowBench)
                    .addComponent(btnDeleteBench))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewBenchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lstBenches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.chooseNewGameDataFile();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLevelDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLevelDownActionPerformed
        moveLevel(-1);
    }//GEN-LAST:event_btnLevelDownActionPerformed

    private void btnLevelUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLevelUpActionPerformed
        moveLevel(1);
    }//GEN-LAST:event_btnLevelUpActionPerformed

    private void btnMonitorDwnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonitorDwnActionPerformed
        PCBuildData.changeMonitor(-1);
        updateCurrentMonitor();
    }//GEN-LAST:event_btnMonitorDwnActionPerformed

    private void btnMonitorUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonitorUpActionPerformed
        PCBuildData.changeMonitor(+1);
        updateCurrentMonitor();
    }//GEN-LAST:event_btnMonitorUpActionPerformed

    private void tbMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbMonitorActionPerformed
        Arrays.asList(this.monitorDisplays).stream().forEach(x->x.setVisible(this.tbMonitor.isSelected()));
    }//GEN-LAST:event_tbMonitorActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        if(this.benches.stream().map(x->x.getBenchName()).collect(Collectors.toList()).contains(this.txtNewBenchName.getText())){
            UIToolBox.popUp(this, this.txtNewBenchName.getText() + " already exists.");
            return;
        }
        
        PCBuilder pc = new PCBuilder(PCBuildData.getGraphicsConfiguration(), this.txtNewBenchName.getText());
        this.benches.add(pc);
        pc.setVisible(true);
        this.updateBenchList();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void lstBenchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lstBenchesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lstBenchesActionPerformed

    private void btnShowBenchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowBenchActionPerformed
        int selIndex = this.lstBenches.getSelectedIndex();
        if(selIndex == -1) return;
        String selVal = this.lstBenches.getItemAt(selIndex);
        
        this.benches.stream().filter(x->x.getBenchName().equals(selVal)).forEach(y->y.setVisible(true));        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowBenchActionPerformed

    private void btnQuickBenchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickBenchActionPerformed
        String bn;
        int count = 1;
        do{
            bn = "Bench " + count++; 
        } while (this.benches.stream().map(x->x.getBenchName()).collect(Collectors.toList()).contains(bn));
        System.out.println("Bench:  " + bn);
        PCBuilder pcb = new PCBuilder(PCBuildData.getGraphicsConfiguration(), bn);
        this.benches.add(pcb);
        pcb.setVisible(true);
        this.updateBenchList();
    }//GEN-LAST:event_btnQuickBenchActionPerformed

    private void btnDeleteBenchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBenchActionPerformed
        if(this.lstBenches.getSelectedIndex() == -1) return;
        PCBuilder pcb = this.benches.get(this.lstBenches.getSelectedIndex());
        this.benches.remove(this.lstBenches.getSelectedIndex());
        pcb.setVisible(false);
        pcb.dispose();
        this.updateBenchList();
        
    }//GEN-LAST:event_btnDeleteBenchActionPerformed

    private void updateCurrentMonitor(){
        this.txtMonitor.setText(Integer.toString(PCBuildData.getMonitor()+1));
    }
    
    private void updateBenchList(){
        String selVal = this.lstBenches.getSelectedIndex() == -1 ? "" : this.lstBenches.getItemAt(this.lstBenches.getSelectedIndex());
        
        
        this.lstBenches.removeAllItems();
        
        this.benches.stream().map(x->x.getBenchName()).forEach(y->this.lstBenches.addItem(y));
        
        System.out.println("Bench items; " + this.benches.size());
    }
    
    
    private void loadGameData() {
        // Pull the game directory location from the registry or apply default.
        String filename = PCBuildData.getSetting("DefaultDir", "C:\\Program Files (x86)\\Steam\\steamapps\\common\\PC Building Simulator");
        this.txtGameFile.setText(filename);
                
        try {
            // Load in the data
            sourceData = new PCBuildSourceData(filename+ "\\PCBS_Data\\sharedassets1.assets");
            PCBuildData.populateHardware(sourceData);
        } catch (IOException ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
            UIToolBox.popUp(this, "There was a problem reading the game file.  Choose your game location and try again.");
        }
        setButtonsEnabled();
    }

    private void chooseNewGameDataFile() {
        if(this.dirChooser.showDialog(this, "Choose PC Builder Game Directory") != 0) return;
        String newLoc = this.dirChooser.getSelectedFile().getAbsolutePath();
        this.txtGameFile.setText(newLoc);
        
        // Try to load in the new game data. - Note to self: Repetative code...
        try {
            // Load in the data
            sourceData = new PCBuildSourceData(newLoc + "\\PCBS_Data\\sharedassets1.assets");
        } catch (IOException ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
            UIToolBox.popUp(this, "There was a problem reading the game file.  Choose your game location and try again.");
            return;
        }
        
        // If you've made it this far, it must be ok.  Save the new file location.
        PCBuildData.setSetting("DefaultDir", this.txtGameFile.getText());
        setButtonsEnabled();
    }
    
    private void setButtonsEnabled(){
        boolean en = !isNull(this.sourceData);
        this.btnCreate.setEnabled(en);

    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDeleteBench;
    private javax.swing.JButton btnLevelDown;
    private javax.swing.JButton btnLevelUp;
    private javax.swing.JButton btnMonitorDwn;
    private javax.swing.JButton btnMonitorUp;
    private javax.swing.JButton btnQuickBench;
    private javax.swing.JButton btnShowBench;
    private javax.swing.JFileChooser dirChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private final javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<String> lstBenches;
    private javax.swing.JToggleButton tbMonitor;
    private javax.swing.JTextField txtGameFile;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtMonitor;
    private javax.swing.JTextField txtNewBenchName;
    // End of variables declaration//GEN-END:variables
}
